"""chat bn userud

Revision ID: 2c70e50cd57b
Revises: 422799895616
Create Date: 2023-08-20 23:49:45.830226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c70e50cd57b'
down_revision: Union[str, None] = '422799895616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'chat_id')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
