"""add chat_id to Personal

Revision ID: 422799895616
Revises: 5d3da61c2a6b
Create Date: 2023-08-19 20:51:14.899458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422799895616'
down_revision: Union[str, None] = '5d3da61c2a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'chat_id')
    # ### end Alembic commands ###
