"""sukass

Revision ID: a644d284a471
Revises: f3ee037e1859
Create Date: 2023-08-15 10:34:22.678711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a644d284a471'
down_revision: Union[str, None] = 'f3ee037e1859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    with op.batch_alter_table('departments') as batch_op:
            batch_op.create_foreign_key('fk_departments_personal', 'personal', ['users_chat_id'], ['user_chat_id'])


        
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('users_chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'personal', ['users_chat_id'], ['user_chat_id'])
    op.drop_column('departments', 'user_chat_id')
    op.add_column('personal', sa.Column('user_chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'personal', 'users', ['user_chat_id'], ['chat_id'])
    # ### end Alembic commands ###

    with op.batch_alter_table('personal') as batch_op:
        batch_op.create_foreign_key('fk_personal_users', 'users', ['user_chat_id'], ['chat_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal', type_='foreignkey')
    op.drop_column('personal', 'user_chat_id')
    op.add_column('departments', sa.Column('user_chat_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'users_chat_id')
    # ### end Alembic commands ###
