"""add personal user

Revision ID: f3ee037e1859
Revises: 3154c2b75143
Create Date: 2023-08-14 01:36:41.833385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ee037e1859'
down_revision: Union[str, None] = '3154c2b75143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('personal', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('personal', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('personal', sa.Column('lavozim', sa.String(), nullable=True))
    op.add_column('personal', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'phone')
    op.drop_column('personal', 'lavozim')
    op.drop_column('personal', 'bio')
    op.drop_column('personal', 'last_name')
    op.drop_column('personal', 'first_name')
    # ### end Alembic commands ###
