"""sukassds

Revision ID: f65fd9287197
Revises: f3ee037e1859
Create Date: 2023-08-16 14:53:41.750726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65fd9287197'
down_revision: Union[str, None] = 'f3ee037e1859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'user_chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('user_chat_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
